### ISSUE TITLE
No complaint if specified dependency doesn't exist

### ISSUE THREAD

**Issue by jcward** [hipponot/bit#6]
I think if a dependency is specified that doesn't exist, it should fail, at least complain.

In the below, I typoed the dependency name, and nothing complained:

![image](https://user-images.githubusercontent.com/2192439/131065150-515d77cd-7e88-460e-ba07-078df1bc38f2.png)

**Comment by skilgoreT** [comment]
with --strict set
<pre><font color="#729FCF">INFO: Writing logs to /tmp/tmp-1324310-o2X5zTFgM2fS, keep_logs is false</font>
<font color="#729FCF">INFO: Computing Dependency Graph</font>
<font color="#EF2929"><b>ERROR: Aborting because missing dependency i_dont_exist in /home/skelly/dev/bit/test/missing_dep/bit.yaml schema --strict</b></font>
 [main][<font color="#4E9A06">~/dev/bit/test/missing_dep]</font>
</pre>
with --no-strict set

<pre><font color="#729FCF">INFO: Writing logs to /tmp/tmp-1323428-7BEUHwyycv66, keep_logs is false</font>
<font color="#729FCF">INFO: Computing Dependency Graph</font>
<font color="#C4A000">WARN: Ignoring missing_dep dependency not in widgets, dependency: i_dont_exist</font>
<font color="#729FCF">INFO: Build Starting</font>
<font color="#729FCF">INFO: Build Status</font>
<font color="#555753">┌────────────────────┬──────────┬──────────┬───────────────┬───────────────┬───────────────┐</font>
<font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>widget</b></font><font color="#CC0000">             </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>succeed</b></font><font color="#CC0000">  </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>duration</b></font><font color="#CC0000"> </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>skipped</b></font><font color="#CC0000">       </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>required</b></font><font color="#CC0000">      </font><font color="#555753">│</font><font color="#CC0000"> </font><font color="#729FCF"><b>rebuilt</b></font><font color="#CC0000">       </font><font color="#555753">│</font>
<font color="#555753">├────────────────────┼──────────┼──────────┼───────────────┼───────────────┼───────────────┤</font>
<font color="#555753">│</font> missing_dep        <font color="#555753">│</font> <font color="#8AE234"><b>true</b></font>     <font color="#555753">│</font> 2.8      <font color="#555753">│</font> false         <font color="#555753">│</font> false         <font color="#555753">│</font> true          <font color="#555753">│</font>
<font color="#555753">└────────────────────┴──────────┴──────────┴───────────────┴───────────────┴───────────────┘</font>
</pre>

**Comment by skilgoreT** [comment]
+ test case` missing_dependency_fails_in_strict_mode`
